### ISSUE TITLE
Phones record on database allows Model to be NULL, app expects NOT NULL

### ISSUE THREAD

**Issue by JLdgu** [JLdgu/PhoneAssistant#17]
System.InvalidOperationException
HResult=-2146233079
Message=The data is NULL at ordinal 4. This method can't be called on NULL values. Check using IsDBNull before calling.
StackTrace:
   at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetString(Int32 ordinal)
   at lambda_method1(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at PhoneAssistant.WPF.Features.Phones.PhonesRepository.GetPhonesAsync() in C:\dev\PhoneAssistant\PhoneAssistant.WPF\Features\Phones\PhonesRepository.cs:line 19
   at PhoneAssistant.WPF.Features.Phones.PhonesMainViewModel.LoadAsync() in C:\dev\PhoneAssistant\PhoneAssistant.WPF\Features\Phones\PhonesMainViewModel.cs:line 256
   at PhoneAssistant.WPF.Features.MainWindow.MainWindowViewModel.UpdateViewAsync(Object selectedViewModelType) in C:\dev\PhoneAssistant\PhoneAssistant.WPF\Features\MainWindow\MainWindowViewModel.cs:line 65
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by JLdgu** [comment]
Closed by release v0.3.10.270

**Comment by JLdgu** [comment]
Closed by release v0.3.10.270
